// console.log("hello");
// let a=10.0;
// console.log(a);
// a="tanu";
// console.log(a);
// a='jonas';
// console.log(a);
// const ab=28;
// console.log(ab);
// ab=45;
// // console.log(ab);
// const agejonas=2037-1991;
// const ageTanu=2022-2002;
// console.log(ageTanu+' '+agejonas);
let a=10;
let b=30;
// console.log('i got '+a+' in/ '+ b);
// console.log(`i got ${a} in ${b}`);

// x=3;
// const ans=x>=30?30:0;
console.log(a**2);